version: "3.9"

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: childbot
      POSTGRES_USER: childbot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [appnet]

  app:
    image: ghcr.io/knopka87/child-bot:main
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: "8080"
      DATABASE_URL: "host=db port=5432 user=childbot password=${POSTGRES_PASSWORD} dbname=childbot sslmode=disable"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}         # можно оставить пустым, если пока polling
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      YC_OAUTH_TOKEN: ${YC_OAUTH_TOKEN}
      YC_FOLDER_ID: ${YC_FOLDER_ID}
    ports:
      - "8080:8080"  # для проверки по IP; позже уберём и повесим HTTPS-прокси
    networks: [appnet]