name: Docker publish

on:
  push:
    branches: [ "main" ]   # при пуше в main
  workflow_dispatch:        # возможность запустить руками из UI

permissions:
  contents: read
  packages: write           # нужно для пуша образа в GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Формируем теги/лейблы; основной тег — "main", дополнительный — короткий SHA
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/llm-proxy
          tags: |
            type=raw,value=main
            type=sha,format=short

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64     # для VDS на x86_64 этого достаточно
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
